version: '2'

services:
  
  nginx:
    restart: always
    build: ./containers/nginx/
    links:
     - php
    ports:
     - "54380:80"
    volumes_from:
     - php

  db:
    restart: always
    build: ./containers/db/
    ports:
     - "54306:3306"
    volumes:
      - ./runtime/db:/var/lib/mysql
    env_file: ./containers/db/.env

  php:
    restart: always
    links:
     - db
    build: ./containers/php/
    volumes:
     - ./app:/app/htdocs
     - ./runtime/logs:/app/log
  php-deamons:
       restart: always
       links:
        - db
       build: ./containers/php-deamons/
       volumes:
        - ./app:/app/htdocs
        - ./runtime/logs:/app/log
